require 'rake'
require 'rake/testtask'

test_tasks = [
    ['all', '*_test.rb']
]

def create_test_task(name, pattern)
    Rake::TestTask.new(name) do |t|
        t.pattern = pattern
        t.verbose = true
        t.warning = true
    end
end

task :default => ["test:all"]

namespace :test do
    test_tasks.each { |t| create_test_task *t }
end
